version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install node@10.15.3 (need right version for `yarn`)
          command: |
            - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
            - nvm install 10.15.3
            - nvm alias default 10.15.3
      - run:
          name: Authenticate with registry
          command: npm run build-auth
      - run: cd ./apps/fomo-native && npm i
      - run: cd ./apps/fomo-native && node .electron-vue/build.js
      - run: cd ./apps/fomo-native && npm run release

workflows:
  version: 2
  build:
    jobs:
      - build

