version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install node@10.15.3 (need right version for `yarn`)
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            chmod 777 /Users/distiller/.bashrc
            /Users/distiller/.bashrc
            nvm install v10.15.3
            nvm alias default v10.15.3

            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Authenticate with registry
          command: npm run build-auth
      - run: cd ./apps/fomo-native && npm i
      - run: cd ./apps/fomo-native && node .electron-vue/build.js
      - run: cd ./apps/fomo-native && npm run release

workflows:
  version: 2
  build:
    jobs:
      - build

