version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: npm run build-auth
      - run: cd ./apps/fomo-native && npm i
      - run: cd ./apps/fomo-native && node .electron-vue/build.js
      - run: cd ./apps/fomo-native && npm run release

workflows:
  version: 2
  build:
    jobs:
      - build

