version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder
    steps:
      - checkout
      - run: node .electron-vue/build.js
      - run: yarn && yarn release

workflows:
  version: 2
  build:
    jobs:
      - build

