version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder
    steps:
      - checkout
      - run: yarn && yarn release

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_windows
      - build_macos
