version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium"
    steps:
      - checkout
      - run: node --version
#      - run: npm run build-auth
      - run:
         command: curl -O https://nodejs.org/dist/latest-v10.x/node-v10.20.1-win-x64.zip
         shell: bash.exe
         name: Download Node v10.20 (.zip)
      - run:
         command: tar -xf node-v10.20.1-win-x64.zip
         shell: powershell.exe
         name: Extract Node v10.20 (.zip)
      - run:
         command: dir && "node-v10.20.1-win-x64/node.exe" --version && where node && pwd
         shell: bash.exe
         name: Test Downloaded Node v10.20 Binary Version
#      - run:
#         command: set PATH=%PATH%;C:\your\path\here\
#         shell: bash.exe
#         name: Append Downloaded Node v10.20 to $PATH
      - run:
         command: npm install @fomobro/talib-fomo
         shell: cmd.exe
         name: Try to Install @fomobro/talib-fomo (in any directory...)
      - run:
         command: cd apps/fomo-native && npm install @fomobro/talib-fomo
         shell: bash.exe
         name: Try to Install @fomobro/talib-fomo (in native directory...)
      - run:
         command: cd apps/fomo-native && npm i
         shell: bash.exe
         name: NPM Install (fomo-native)
      - run:
         command: cd apps/fomo-native && node .electron-vue/build.js
         shell: bash.exe
         name: Electron Build
      - run:
         command: cd apps/fomo-native && npm run release
         shell: bash.exe
         name: NPM Release (fomo-native)

#version: 2
#jobs:
#  build:
#    macos:
#      xcode: "10.0.0"
#    steps:
#      - checkout
#      - run: node --version
#      - run: which node
##      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
##      - run: nvm install 10.15.3
##      - run: nvm alias default 10.15.3
#      - run:
#          name: Authenticate with registry
#          command: npm run build-auth
#      - run: cd ./apps/fomo-native && npm i
#      - run: cd ./apps/fomo-native && node .electron-vue/build.js
#      - run: cd ./apps/fomo-native && npm run release
#    windows:
#    steps:
#      - checkout
#      - run: node --version
#      - run:
#          name: Authenticate with registry
#          command: npm run build-auth
#      - run: cd ./apps/fomo-native && npm i
#      - run: cd ./apps/fomo-native && node .electron-vue/build.js
#      - run: cd ./apps/fomo-native && npm run release
#
#workflows:
#  version: 2
#  build:
#    jobs:
#      - build
#
