version: 2
jobs:
  build:
    macos:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn
      - run: node .electron-vue/build.js
      - run: yarn release

workflows:
  version: 2
  build:
    jobs:
      - build

