version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn release --win

  build_linux:
    docker:
      - image: electronuserland/builder
    steps:
      - checkout
      - run: yarn && yarn release --linux

  build_macos:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: yarn && yarn release --mac

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_windows
      - build_macos
